Oak-City-Shredders/oak-city-event-app

ios/App/App/Info.plist

So we don't have to approve builds each time in TestFlight

compliance fix

---

src/App.tsx
src/pages/Map.tsx
src/pages/SchedulePage.tsx

This allows you to click on a location in the schedule and then be shown the Map with a label on it.  Needs work, but fun concept.

add map labels

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json

We can't upload any more 1.0 builds to Apple Store.

increment version

---

package-lock.json
package.json
src/components/StokeMeter.css
src/components/StokeMeter.tsx
src/hooks/useGoogleCalendar.ts
src/hooks/useGoogleSheets.ts
src/pages/Home.tsx
src/pages/SchedulePage.tsx

A really quick and dirty stoke meter.  Get ready to be stoked!

Stoke meter

---

src/pages/Home.tsx

feat(navigation): add side nav

---

src/components/StokeMeter.tsx
src/pages/Home.tsx
src/pages/Map.tsx
src/pages/ScavengerHunt.tsx

Closes #90 
Closes #81
Closes #88

Bug fixes 

---

src/components/PageHeader.tsx
src/pages/About.tsx
src/pages/DripSchedule.tsx
src/pages/EmergencyServices.tsx
src/pages/FoodTrucks.tsx
src/pages/Home.tsx
src/pages/Login.tsx
src/pages/Map.tsx
src/pages/Notifications.tsx
src/pages/Quests.tsx
src/pages/Racing.tsx
src/pages/Raffles.tsx
src/pages/ScavengerHunt.tsx
src/pages/SchedulePage.tsx
src/pages/TrickComp.tsx

back button navigation

---

src/pages/Notifications.tsx

Now you can add a description in the notification Google sheet.

add notification details

---

src/components/DynamicContent.tsx
src/hooks/useGoogleSheets.ts
src/pages/Home.tsx

By adding content to this sheet update the Home Page:
https://docs.google.com/spreadsheets/d/1b04PyTyJzrf-PfHEEarWv8p77zBOsztkzRM4fVAhZLw/edit?gid=1477815879#gid=1477815879

Dynamic content

---

src/pages/EmergencyServices.css
src/pages/EmergencyServices.tsx

[issue 112](https://github.com/Oak-City-Shredders/oak-city-event-app/issues/112)

fix(emergency-services): add details

---

src/components/Map.css
src/components/Map.tsx
src/pages/MapPage.tsx

make labels white with black border

use local storage for map filters

---

src/components/NotificationToggle.tsx
src/pages/Racing.tsx
src/pages/ScavengerHunt.tsx

refactor notification topics to a component

---

src/components/StokeMeter.tsx
src/hooks/useLocalStorage.ts
src/hooks/usePreferenceSettings.ts
src/pages/Home.tsx
src/pages/Login.tsx

Added the ability to disable some of the components on the home page

---

android/app/src/main/AndroidManifest.xml
ios/App/App/Info.plist
src/App.tsx
src/components/ErrorBoundary.tsx
src/main.tsx
src/pages/About.tsx
src/pages/DripSchedule.css
src/pages/DripSchedule.tsx
src/pages/MapPage.tsx
src/pages/Quests.tsx
src/pages/Racing.css
src/pages/Racing.tsx
src/pages/SchedulePage.tsx
src/utils/analytics.ts

Lock portrait

---

src/App.tsx
src/auth.ts
src/components/DynamicContent.tsx
src/components/FoodTruckSwiper.tsx
src/components/HomePageMenu.tsx
src/components/RacerSpotlight.tsx
src/context/AuthContext.tsx
src/hooks/useFireStoreDB.ts
src/pages/Home.tsx
src/pages/Login.module.css
src/pages/Login.tsx
src/pages/TicketsPage.module.css
src/pages/TicketsPage.tsx

This is a first step to hopefully showing tickets to users who have verified their email.

verifyemail

---

.github/workflows/build-ios.yml
.github/workflows/pr-check.yml

Force xcode version up to 16

---

src/components/FoodTruckSwiper.tsx
src/components/Map.tsx
src/components/TicketCounter.tsx
src/pages/FireBaseAppCheckPage.tsx
src/pages/ScavengerHunt.tsx
src/pages/SchedulePage.tsx
src/pages/Sponsors.tsx

Error handling auth

---

src/pages/MapPage.tsx

add refresh and back button for map

---

src/App.tsx
src/components/CountdownTimer.tsx

| Improvements       | Percent | Difference        |
|------------|-----|-------------------|
| Decreased load time      | 25%  | 12 sec > 9 sec |
| Decreased initial render time        | 30%  | 12 sec > 8 sec          |
| Decreased network load    | 21%  | 11.5MB > 9MB  |
Had to update the countdown timer becuase it was relying on the dayjs plugin already being registered in other components. Now that we are lazy loading, it's isolated. 
Also updated some of the logic that claude.ai found issues with.

fix(lazy-loading): implement lazy loading

---

src/App.tsx
src/components/CountdownTimer.tsx

Reverts Oak-City-Shredders/oak-city-event-app#400

Revert "fix(lazy-loading): implement lazy loading"

---

src/pages/About.tsx

fix(about): add details to the about page

---

src/App.tsx

fix(tab-bar): add racing to the main tab bar

---

src/components/NotificationToggle.tsx
src/components/NotificationsCard.tsx
src/pages/Login.module.css
src/pages/Login.tsx
src/pages/Racing.tsx
src/pages/SchedulePage.tsx
src/pages/TrickComp.tsx

fix(notifications): refactor to put in login menu under preferences

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj

This PR bumps the app version to 1.0.9 for the next App Store release.

Release: Bump app version to 1.0.9

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj

This PR bumps the app version to 1.0.10 for the next App Store release.

Release: Bump app version to 1.0.10

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj

This PR bumps the app version to 1.0.11 for the next App Store release.

Release: Bump app version to 1.0.11

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj

This PR bumps the app version to 1.1.0 for the next App Store release.

Release: Bump app version to 1.1.0

---

src/context/CurrentEventContext.tsx
src/hooks/useFireStoreDB.ts
src/hooks/useGoogleCalendar.ts
src/hooks/useNotifications.ts
src/pages/Events.tsx
src/pages/Notifications.tsx

This will register the device for notifications when the eventId changes

feat(notification-for-events): support notifications for casual campout

---

src/components/CountdownTimer.tsx
src/components/TicketCounter.module.css
src/components/TicketCounter.tsx
src/pages/Home.tsx

Made ticket counter better for when ticket integration isn't in place (doesn't prompt for sign in or to show tickets)
Also added countdown and made it generic for other festivals

Ticket counter event info

---

src/App.tsx
src/hooks/useBands.ts
src/pages/Bands.tsx

feat(bands): add new bands page for casual campout

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj

This PR bumps the app version to 1.1.2 for the next App Store release.

Release: Bump app version to 1.1.2

---

.eslintrc.cjs
package-lock.json
package.json
src/App.tsx
src/components/HomePageMenu.tsx
src/components/NotificationToggle.tsx
src/components/RacerSpotlight.tsx
src/components/UnderConstruction.tsx
src/hooks/useNotifications.ts
src/hooks/usePreferenceSettings.ts
src/pages/About.tsx
src/pages/DiscGolfScorecard.tsx
src/pages/DripSchedule.tsx
src/pages/EmergencyServices.tsx
src/pages/FireBaseAppCheckPage.tsx
src/pages/FoodTrucks.tsx
src/pages/Quests.tsx
src/pages/RacerProfile.tsx
src/pages/Racing.tsx
src/pages/ScavengerHunt.tsx
src/pages/Team.tsx
src/pages/TicketsPage.tsx

- Added unused imports plugin for eslint to auto fix them
- Removed unused imports

fix(lint): remove unused imports
